### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by aldentantan**
- Added "Back to top" hyperlink after each section
- Changed outdated images to current UI
- Hopefully fixed glossary table

### CODE REVIEW

**Comment by aldentantan** [comment]
Will push DG updates to this PR soon, don't have to merge yet

**Review by saajidshaik02 — COMMENTED** [review]
LGTM!

**Review by saajidshaik02 — COMMENTED** [review]
LGTM!

**Review by saajidshaik02 — APPROVED** [review]
LGTM!

**Pull request merged**
